export const BLOG_POSTS = [
    {
        slug: 'what-is-board-and-train-dog-training',
        title: 'What Is Board & Train Dog Training? A Complete Guide',
        metaTitle: 'What Is Board & Train Dog Training? | Shepards K9',
        metaDesc: 'Learn everything about board and train dog training — how it works, what to expect, and whether it\'s right for your dog. Expert guide from Shepards K9.',
        h1: 'What Is Board & Train Dog Training? A Complete Guide',
        excerpt: 'Board & Train is one of the most effective dog training methods available — but it\'s also one of the most misunderstood. Here\'s everything you need to know.',
        date: '2024-11-01',
        readTime: '7 min read',
        relatedService: '/board-and-train',
    },
    {
        slug: 'board-and-train-vs-regular-dog-training',
        title: 'Board & Train vs Regular Dog Training: Which Is Better?',
        metaTitle: 'Board & Train vs Regular Dog Training | Shepards K9 Murrieta',
        metaDesc: 'Comparing board and train programs to weekly lessons and group classes. Which gets faster results? Which lasts longer? Honest breakdown from Shepards K9.',
        h1: 'Board & Train vs Regular Dog Training: Which Is Better?',
        excerpt: 'Weekly lessons, group classes, and board & train all promise results. But which one actually delivers? We break down the honest pros and cons of each.',
        date: '2024-10-15',
        readTime: '8 min read',
        relatedService: '/board-and-train',
    },
    {
        slug: 'how-much-does-dog-training-cost-murrieta',
        title: 'How Much Does Dog Training Cost in Murrieta, CA?',
        metaTitle: 'Dog Training Cost in Murrieta, CA | Shepards K9',
        metaDesc: 'Wondering what dog training costs in Murrieta? We break down pricing for board & train, day training, off-leash training, and more. Transparent guide from Shepards K9.',
        h1: 'How Much Does Dog Training Cost in Murrieta, CA?',
        excerpt: 'Dog training prices in Murrieta vary significantly. Here\'s a transparent breakdown of what to expect — and what to watch out for.',
        date: '2024-09-20',
        readTime: '6 min read',
        relatedService: '/pricing',
    },
    {
        slug: 'what-is-day-training-for-dogs',
        title: 'What Is Day Training for Dogs? How It Works & Who It\'s For',
        metaTitle: 'What Is Day Training for Dogs? | Shepards K9 Murrieta',
        metaDesc: 'Dog day training explained — how it works, what your dog learns, and whether it\'s right for busy owners. From Shepards K9 in Murrieta, CA.',
        h1: 'What Is Dog Day Training and How Does It Work?',
        excerpt: 'Day Training is perfect for busy dog owners. Eduardo trains your dog during the day while you work. Here\'s exactly what to expect.',
        date: '2024-08-25',
        readTime: '5 min read',
        relatedService: '/day-training',
    },
    {
        slug: 'off-leash-dog-training-guide',
        title: 'The Complete Guide to Off Leash Dog Training in Southern California',
        metaTitle: 'Off Leash Dog Training Guide | Shepards K9 Murrieta',
        metaDesc: 'Everything you need to know about off-leash dog training — foundation skills, common mistakes, and how to achieve real-world reliability. From Shepards K9.',
        h1: 'The Complete Guide to Off Leash Dog Training',
        excerpt: 'True off-leash reliability is the gold standard in dog training. Here\'s how to achieve it the right way — and what most trainers get wrong.',
        date: '2024-07-10',
        readTime: '9 min read',
        relatedService: '/off-leash-training',
    },
    {
        slug: 'best-dog-boarding-murrieta-temecula',
        title: 'Best Dog Boarding in Murrieta & Temecula: What to Look For',
        metaTitle: 'Best Dog Boarding Murrieta & Temecula | Shepards K9',
        metaDesc: 'Looking for the best dog boarding near Murrieta or Temecula? Here\'s what separates great in-home boarding from a crowded kennel. Guide from Shepards K9.',
        h1: 'Best Dog Boarding in Murrieta & Temecula: What You Need to Know',
        excerpt: 'Not all dog boarding is created equal. Here\'s what to look for when choosing between kennels, pet hotels, and in-home boarding in the Murrieta area.',
        date: '2024-06-18',
        readTime: '6 min read',
        relatedService: '/dog-boarding',
    },
    {
        slug: 'dog-training-company-vs-independent-trainer',
        title: 'Dog Training Company vs Independent Trainer: Which Is Better?',
        metaTitle: 'Dog Training Company vs Independent Trainer | Shepards K9',
        metaDesc: 'Should you hire a big dog training company or an independent trainer like Eduardo Beltran? Honest comparison with pros and cons of each approach.',
        h1: 'Dog Training Company vs Independent Trainer: The Honest Comparison',
        excerpt: 'Big franchise training companies promise consistency. Independent trainers promise personal attention. Here\'s what the data actually shows.',
        date: '2024-05-22',
        readTime: '7 min read',
        relatedService: '/dog-training-company',
    },
    {
        slug: 'how-to-choose-dog-trainer-murrieta',
        title: 'How to Choose the Right Dog Trainer in Murrieta, CA',
        metaTitle: 'How to Choose a Dog Trainer in Murrieta | Shepards K9',
        metaDesc: 'Choosing a dog trainer in Murrieta? Here\'s a step-by-step guide to avoid red flags, ask the right questions, and find someone you can actually trust.',
        h1: 'How to Choose the Right Dog Trainer in Murrieta, CA',
        excerpt: 'There are a lot of dog trainers in the Murrieta and Temecula area. Here\'s exactly how to separate the professionals from the pretenders.',
        date: '2024-04-14',
        readTime: '8 min read',
        relatedService: '/dog-training-company',
    },
];
