export const REVIEWS = [
    {
        author: 'Sarah M.',
        location: 'Murrieta, CA',
        rating: 5,
        text: 'Eduardo is absolutely amazing. Our German Shepherd Titan was jumping on everyone and pulling on leash. After 3 weeks of Board & Train, he walks perfectly beside me, comes when called off-leash, and is just an all-around better dog. Worth every single penny.',
        service: 'Board & Train',
        date: '2024-11-15',
    },
    {
        author: 'Jason R.',
        location: 'Temecula, CA',
        rating: 5,
        text: 'My dog Luna was reactive and anxious around other dogs. Eduardo worked with her patiently for a month and the transformation is unbelievable. She can now walk past dogs on trails without a meltdown. Eduardo genuinely cares about the dogs he works with.',
        service: 'Board & Train',
        date: '2024-10-08',
    },
    {
        author: 'Maria L.',
        location: 'Menifee, CA',
        rating: 5,
        text: 'We used Eduardo for dog boarding while we went on vacation and we couldn\'t be happier. Our dog Biscuit was treated like family. Eduardo sent us daily updates and photos. No kennel cough, no stress — just a happy, well-rested dog when we picked him up.',
        service: 'Dog Boarding',
        date: '2024-09-22',
    },
    {
        author: 'Chris T.',
        location: 'Wildomar, CA',
        rating: 5,
        text: 'I tried two other trainers before Eduardo and nothing stuck. With Eduardo it clicked within the first week. My Blue Heeler Max now responds to voice commands off-leash on trails. The difference is Eduardo builds a RELATIONSHIP with your dog, not just commands.',
        service: 'Off Leash Training',
        date: '2024-08-30',
    },
    {
        author: 'Alicia B.',
        location: 'Carlsbad, CA',
        rating: 5,
        text: 'Day Training was a game changer for our family. We both work full-time and couldn\'t commit to group classes. Eduardo picked up our Golden Retriever every day for 3 weeks and trained her while we were at work. She came home a different dog each evening. Highly recommend!',
        service: 'Day Training',
        date: '2024-12-01',
    },
    {
        author: 'David K.',
        location: 'Lake Elsinore, CA',
        rating: 5,
        text: 'Eduardo is the real deal. Knowledgeable, patient, truly loves dogs. Our rescue had severe leash reactivity and aggression. Other trainers turned us away. Eduardo took the case, worked with her for 4 weeks, and we have a completely different dog. Can\'t recommend him enough.',
        service: 'Board & Train',
        date: '2024-07-14',
    },
];
