export const SERVICES = [
    {
        id: 'dog-training',
        name: 'Dog Training',
        shortDesc: 'Comprehensive, relationship-based dog training designed for real-world reliability. From basic manners to complex behavioral issues.',
        href: '/dog-training',
        featured: false,
        isCore: true,
        icon: '🦮',
        image: '/photos/hero-eduardo-boxer.jpg',
        metaTitle: 'Expert Dog Training in Murrieta, CA | Shepards K9',
        metaDesc: 'Professional dog training in Murrieta, CA. Eduardo Beltran offers relationship-based training for all breeds. Real results, real environments. Call 818-255-8728.',
        h1: 'Expert Dog Training in Murrieta, CA',
    },
    {
        id: 'board-and-train',
        name: 'Board & Train',
        shortDesc: 'Your dog lives with Eduardo and trains daily in real-world environments. The most effective, fastest-result service we offer.',
        href: '/board-and-train',
        featured: true,
        isCore: true,
        icon: '🏡',
        image: '/photos/IMG_8911.JPG',
        metaTitle: 'Board & Train Dog Training in Murrieta, CA | Shepards K9',
        metaDesc: 'Murrieta\'s top Board & Train program. Your dog lives and trains with Eduardo for rapid, lasting results. Free estimate. Call 818-255-8728.',
        h1: 'Board & Train Dog Training in Murrieta, CA',
    },
    {
        id: 'puppy-training',
        name: 'Puppy Training',
        shortDesc: 'Start your puppy off right. Foundation skills, socialization, and bite inhibition delivered with patience and love.',
        href: '/puppy-training',
        featured: false,
        isCore: true,
        icon: '🐶',
        image: '/photos/IMG_0416.JPG',
        metaTitle: 'Puppy Training in Murrieta, CA | Shepards K9',
        metaDesc: 'Expert puppy training in Murrieta, CA. Foundation skills, housebreaking & socialization. Start strong with Shepards K9 — 818-255-8728.',
        h1: 'Puppy Training in Murrieta, CA',
    },
    {
        id: 'obedience-training',
        name: 'Obedience Training',
        shortDesc: 'Heel, sit, stay, come — on your terms, in the real world, not just a training room.',
        href: '/obedience-training',
        featured: false,
        isCore: true,
        icon: '🎓',
        image: '/photos/IMG_8720.jpg',
        metaTitle: 'Obedience Training in Murrieta, CA | Shepards K9',
        metaDesc: 'Professional dog obedience training in Murrieta, CA. Reliable commands in real-world settings. Licensed & insured. Call 818-255-8728.',
        h1: 'Dog Obedience Training in Murrieta, CA',
    },
    {
        id: 'off-leash-training',
        name: 'Off Leash Training',
        shortDesc: 'Freedom you can trust. Real off-leash reliability built through progressive training in parks, trails, and everyday environments.',
        href: '/off-leash-training',
        featured: false,
        isCore: true,
        icon: '🎾',
        image: '/photos/IMG_0320.JPG',
        metaTitle: 'Off Leash Dog Training in Murrieta, CA | Shepards K9',
        metaDesc: 'Achieve real off-leash freedom with Shepards K9 in Murrieta. Proven training in real environments. Licensed & insured. Call 818-255-8728.',
        h1: 'Off Leash Dog Training in Murrieta, CA',
    },
    {
        id: 'day-training',
        name: 'Day Training',
        shortDesc: 'Eduardo trains your dog during the day while you\'re at work. Drop off in the morning, pick up a better dog in the evening.',
        href: '/day-training',
        featured: false,
        isCore: true,
        icon: '☀️',
        image: '/photos/IMG_9491.JPG',
        metaTitle: 'Dog Day Training in Murrieta, CA | Shepards K9',
        metaDesc: 'Dog Day Training in Murrieta, CA. Eduardo trains your dog while you\'re at work. Real results without you lifting a finger. Call 818-255-8728.',
        h1: 'Dog Day Training in Murrieta, CA',
    },
    {
        id: 'dog-boarding',
        name: 'Dog Boarding',
        shortDesc: 'Safe, loving dog boarding in a real home environment — not a kennel. Your dog is family here.',
        href: '/dog-boarding',
        featured: true,
        isCore: true,
        icon: '🐾',
        image: '/photos/dog-boarding-indoor.jpg',
        metaTitle: 'Dog Boarding in Murrieta, CA | Shepards K9',
        metaDesc: 'Premium in-home dog boarding in Murrieta. Your dog stays in a loving home, not a cold kennel. Call 818-255-8728 for availability.',
        h1: 'Dog Boarding in Murrieta, CA',
    },
    {
        id: 'pickup-and-drop-off',
        name: 'Pickup & Drop Off',
        shortDesc: 'No time to drive? We come to you. Convenient pickup and drop-off service for all training programs.',
        href: '/pickup-and-drop-off',
        featured: false,
        isUtility: true,
        icon: '🚗',
        image: '/photos/IMG_8737-2.jpg',
        metaTitle: 'Dog Training Pickup & Drop Off Murrieta | Shepards K9',
        metaDesc: 'Convenient dog training pickup & drop off in Murrieta, CA. We come to you. Schedule with Shepards K9 today — 818-255-8728.',
        h1: 'Dog Training Pickup & Drop Off in Murrieta, CA',
    },
    {
        id: 'dog-photography',
        name: 'Dog Photography',
        shortDesc: 'Professional photos of your dog in Southern California\'s most scenic locations. Eduardo\'s eye for dogs makes every shot natural, not posed.',
        href: '/dog-photography',
        featured: false,
        isUtility: true,
        icon: '📸',
        image: '/photos/dog-photography-corgi.jpg',
        metaTitle: 'Professional Dog Photography in Murrieta | Shepards K9',
        metaDesc: 'Professional photos of your dog in Southern California\'s most scenic locations. Natural, unposed shots catching your dog in action.',
        h1: 'Professional Dog Photography in Murrieta',
    },
];

export const SERVICE_DROPDOWN_OPTIONS = [
    'Dog Training',
    'Board & Train',
    'Dog Boarding',
    'Day Training',
    'Off Leash Training',
    'Pickup & Drop Off',
    'Puppy Training',
    'Obedience Training',
    'Dog Photography',
    'Other',
];
